version: "3"
services:
  mysql:
    hostname: mysql
    image: mysql:8.0.15
    container_name: my-sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=simcord
    ports:
      - 3307:3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.7.14-management-alpine
    container_name: rmq-man
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15673:15672
      - 5673:5672